#publish your docker image to github container registry
name: publish
on: [push]
jobs:
  publish-bal-tests-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the bal-tests Docker image
        run: |
          docker build . --tag ghcr.io/miranlfk/bal-tests:latest
          docker run ghcr.io/miranlfk/bal-tests:latest
          docker push ghcr.io/miranlfk/bal-tests:latest
          